apiVersion: v1
kind: PersistentVolume
metadata:
  name: nvbenfs
  labels:
    site: nickveenhofbe
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.3.247.140
    path: "/nickveenhofbe"