apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal8
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal8
    spec:
      containers:
        - image: richarvey/nginx-php-fpm:php71
          env:
            - name: GIT_EMAIL
              value: nick.veenhof@gmail.com
            - name: GIT_NAME
              value: 'Nick Veenhof'
            - name: GIT_USERNAME
              value: 'nick_vh'
            - name: ERRORS
              value: '0'
            - name: GIT_REPO
              value: 'gitlab.com/nick_vh/nickveenhof.be.git'
            - name: GIT_PERSONAL_TOKEN
              value: 'z5pGuuCa3tZXaN4QkUpy'
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
              # Connect to the SQL proxy over the local network on a fixed port.
              # Insert the port number used by your database. 
            - name: DB_HOST
              value: 127.0.0.1:3306
            - name: DB_NAME
              # Connect to the SQL proxy over the local network on a fixed port.
              # Insert the port number used by your database. 
              value: drupal
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
          name: drupal8
          ports:
            - containerPort: 80
              name: drupal-http
          volumeMounts:
          #    # Name must match the volume name below.
            - name: drupal-persistent-storage
          #    # Mount path within the container.
              mountPath: /var/www/html
        # Change [INSTANCE_CONNECTION_NAME] here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # Insert the port number used by your database.
        # [START proxy_container]
        - image: b.gcr.io/cloudsql-docker/gce-proxy:1.05
          resources:
              limits:
                cpu: 0.01
          name: cloudsql-proxy
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=drupalcontainerengine:europe-west1:drupal=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      # [END proxy_container]
    # [START volumes]
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
        - name: drupal-persistent-storage
          gcePersistentDisk:
      #      # This GCE persistent disk must already exist.
            pdName: drupal-disk
            fsType: ext4
