apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared1-200gb
  annotations:
    volume.alpha.kubernetes.io/storage-class: standard
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 200Gi