kind: PersistentVolume
apiVersion: v1
metadata:
  name: mypv
spec:
  capacity:
    storage: 95Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: "persistent-disk"
    fsType: "ext4"