apiVersion: v1
kind: Service
metadata:
  labels:
    name: php-nginx
  name: php-nginx
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      protocol: TCP
  selector:
    service: php-nginx